-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 14:41:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restau_app
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `restau_app` ;

-- -----------------------------------------------------
-- Schema restau_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restau_app` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restau_app` ;

-- -----------------------------------------------------
-- Table `restau_app`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restau_app`.`address` ;

CREATE TABLE IF NOT EXISTS `restau_app`.`address` (
  `addressid` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `town` VARCHAR(45) NOT NULL,
  `quarter` VARCHAR(45) NOT NULL,
  `waiters_waiterid` INT NOT NULL,
  `waiters_orders_orderid` INT NOT NULL,
  `customers_customerid` INT NOT NULL,
  `customers_orders_orderid` INT NOT NULL,
  PRIMARY KEY (`addressid`, `waiters_waiterid`, `waiters_orders_orderid`, `customers_customerid`, `customers_orders_orderid`),
  UNIQUE INDEX `addressid_UNIQUE` (`addressid` ASC) VISIBLE,
  INDEX `fk_address_waiters1_idx` (`waiters_waiterid` ASC, `waiters_orders_orderid` ASC) VISIBLE,
  INDEX `fk_address_customers1_idx` (`customers_customerid` ASC, `customers_orders_orderid` ASC) VISIBLE,
  CONSTRAINT `fk_address_waiters1`
    FOREIGN KEY (`waiters_waiterid` , `waiters_orders_orderid`)
    REFERENCES `restau_app`.`waiters` (`waiterid` , `orders_orderid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_customers1`
    FOREIGN KEY (`customers_customerid` , `customers_orders_orderid`)
    REFERENCES `restau_app`.`customers` (`customerid` , `orders_orderid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restau_app`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restau_app`.`category` ;

CREATE TABLE IF NOT EXISTS `restau_app`.`category` (
  `categoryid` INT NOT NULL AUTO_INCREMENT,
  `categoryname` VARCHAR(45) NOT NULL,
  `dishes_dishid` INT NOT NULL,
  PRIMARY KEY (`categoryid`, `dishes_dishid`),
  INDEX `fk_category_dishes1_idx` (`dishes_dishid` ASC) VISIBLE,
  CONSTRAINT `fk_category_dishes1`
    FOREIGN KEY (`dishes_dishid`)
    REFERENCES `restau_app`.`dishes` (`dishid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restau_app`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restau_app`.`customers` ;

CREATE TABLE IF NOT EXISTS `restau_app`.`customers` (
  `customerid` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `createdat` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `orders_orderid` INT NOT NULL,
  PRIMARY KEY (`customerid`, `orders_orderid`),
  INDEX `fk_customers_orders_idx` (`orders_orderid` ASC) VISIBLE,
  CONSTRAINT `fk_customers_orders`
    FOREIGN KEY (`orders_orderid`)
    REFERENCES `restau_app`.`orders` (`orderid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restau_app`.`dishes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restau_app`.`dishes` ;

CREATE TABLE IF NOT EXISTS `restau_app`.`dishes` (
  `dishid` INT NOT NULL AUTO_INCREMENT,
  `dishaname` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dishid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restau_app`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restau_app`.`orders` ;

CREATE TABLE IF NOT EXISTS `restau_app`.`orders` (
  `orderid` INT NOT NULL AUTO_INCREMENT,
  `createdat` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`orderid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restau_app`.`restaurants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restau_app`.`restaurants` ;

CREATE TABLE IF NOT EXISTS `restau_app`.`restaurants` (
  `restaurantname` VARCHAR(45) NOT NULL,
  `dateofarrival` VARCHAR(45) NOT NULL,
  `dateofpreparation` VARCHAR(45) NOT NULL,
  `address_addressid` INT NOT NULL,
  `address_waiters_waiterid` INT NOT NULL,
  `address_waiters_orders_orderid` INT NOT NULL,
  `address_customers_customerid` INT NOT NULL,
  `address_customers_orders_orderid` INT NOT NULL,
  `transfers_transferid` INT NOT NULL,
  PRIMARY KEY (`restaurantname`, `transfers_transferid`),
  INDEX `fk_restaurants_address1_idx` (`address_addressid` ASC, `address_waiters_waiterid` ASC, `address_waiters_orders_orderid` ASC, `address_customers_customerid` ASC, `address_customers_orders_orderid` ASC) VISIBLE,
  INDEX `fk_restaurants_transfers1_idx` (`transfers_transferid` ASC) VISIBLE,
  CONSTRAINT `fk_restaurants_address1`
    FOREIGN KEY (`address_addressid` , `address_waiters_waiterid` , `address_waiters_orders_orderid` , `address_customers_customerid` , `address_customers_orders_orderid`)
    REFERENCES `restau_app`.`address` (`addressid` , `waiters_waiterid` , `waiters_orders_orderid` , `customers_customerid` , `customers_orders_orderid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurants_transfers1`
    FOREIGN KEY (`transfers_transferid`)
    REFERENCES `restau_app`.`transfers` (`transferid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restau_app`.`transfers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restau_app`.`transfers` ;

CREATE TABLE IF NOT EXISTS `restau_app`.`transfers` (
  `transferid` INT NOT NULL AUTO_INCREMENT,
  `transfersdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`transferid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restau_app`.`waiters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restau_app`.`waiters` ;

CREATE TABLE IF NOT EXISTS `restau_app`.`waiters` (
  `waiterid` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `salary` INT NULL DEFAULT NULL,
  `orders_orderid` INT NOT NULL,
  PRIMARY KEY (`waiterid`, `orders_orderid`),
  INDEX `fk_waiters_orders1_idx` (`orders_orderid` ASC) VISIBLE,
  CONSTRAINT `fk_waiters_orders1`
    FOREIGN KEY (`orders_orderid`)
    REFERENCES `restau_app`.`orders` (`orderid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
